---
title: "Introductory course"
author: "Matvienko_YuD"
date: "`r Sys.Date()`"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)

library(tidyverse)
library(flextable)
library(DescTools)

library(psych)
library(ggplot2)
library(ggcorrplot)

library(ggpubr)
```

```{r include=FALSE}
data <- read_tsv("C:/Users/Asus/Desktop/IB/BioStat_2023/GitHub/raw/data_tsv.tsv")
spec(data)
data$Группа <- as.factor(data$Группа)
data$Пол <- as.factor(data$Пол)
data$`Группа крови` <- as.factor(data$`Группа крови`)
```

```{r}
statistics <- list(
  `Количество субъектов` = ~length(.x) %>% as.character(),
  `Количество (есть данные)` = ~sum(!is.na(.x)) %>% as.character(),
  `Нет данных` = ~sum(is.na(.x)) %>% as.character(),
  `Ср. знач.` = ~ifelse(sum(!is.na(.x)) == 0, "Н/П*", mean(.x, na.rm = TRUE) %>% round(2) %>% as.character()),
  `Станд. отклон.` = ~ifelse(sum(!is.na(.x)) < 3, "Н/П*", sd(.x, na.rm = TRUE) %>% round(2) %>% as.character()),
  `95% ДИ для среднего` = ~sd(.x, na.rm = TRUE) %>% round(2) %>% as.character(),
  `мин. - макс.` = ~ifelse(sum(!is.na(.x)) == 0, "Н/П*", paste0(min(.x, na.rm = TRUE) %>% round(2), " - ", max(.x, na.rm = TRUE) %>% round(2)) %>% as.character()),
  `Медиана` = ~ifelse(sum(!is.na(.x)) == 0, "Н/П*", median(.x, na.rm = TRUE) %>% round(2) %>% as.character()),
  `Q1 - Q3` = ~ifelse(sum(!is.na(.x)) == 0, "Н/П*", paste0(quantile(.x, 0.25, na.rm = TRUE) %>% round(2), " - ", quantile(.x, 0.75, na.rm = TRUE) %>% round(2)) %>% as.character())
)

data %>%
  select(`Группа`, where(is.numeric)) %>%
  group_by(`Группа`) %>%
  summarize(across(where(is.numeric), statistics)) %>%
  pivot_longer(!`Группа`) %>%
  separate(name, into = c("Переменная", "Статистика"), sep = "_") %>%
  rename(`Значение` = value)
```


